### ISSUE TITLE
Linux: Pointing device too fast

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [moonlight-stream/moonlight-qt#126]
**Describe the bug**
The mouse pointer is way too fast.

**Steps to reproduce**
- install Moonlight via flatpak
- Run Moonlight via flatpak
- Start any application

**Moonlight settings (please complete the following information)**
- default

**Client PC details (please complete the following information)**
 - OS: Linux 4.18
 - Moonlight Version: 0.6.2
 - GeForce Experience: 3.15.0.164

**Logs (please attach)**
[log.txt](https://github.com/moonlight-stream/moonlight-qt/files/2554417/log.txt)

**Additional context**
```
xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    3200x1800 pixels (846x476 millimeters)
  resolution:    96x96 dots per inch
```
Calculated resolution at 14" is 262 dpi

**Comment by cgutman** [comment]
What mouse are you using?

Can you try checking the "enable mouse acceleration" box?

**Comment by ihatemicrosoft-was-already-taken** [comment]
OK, so I have re-tested a bit.

When using a proper mouse (Logitech G603 via Bluetooth) the pointer speed is OK. However, when using the touchpad as pointing device the cursor speed is way too fast. The mouse cursor moves faster in Moonlight than on my normal Linux desktop (i.e. the mouse cursor will travel around twice as far when dragging a finger the same amount on my touchpad.

I have experimented with the mouse acceleration setting. Enabling this will make the touchpad actually useable, but then the "real" mouse will become way too fast.

I hope you can make sense of my description.

**Comment by cgutman** [comment]
Can you try again with the latest Flatpak?

Somebody reported that their mouse movement was fixed when we updated to Qt 5.12.

You can also try the Snap package and see if it has the same issue.

**Comment by Paralda** [comment]
I can confirm this same problem on Ubuntu 19.10 using a Logitech g503 proteus mouse plugged in via USB. 

Should I try using the flatpak instead of the snap? Note: this doesn't seem to be a problem inside of full screen games, but any windowed-fullscreen games or the desktop definitely have this issue.

**Comment by Nixellion** [comment]
Also got similar issue on Ubuntu 20.04. At first noticed mouse was ignoring acceleration, went ahead and clicked the "Optimize for remote desktop" checkbox. Now acceleration is clearly working, however mouse is moving much faster compared to how it works outside of moonlight. It could be closer to how the mouse is set up on the remote PC I'm connecting to though, but I would expect sensitivity to be the same as on the client I'm connecting FROM.

**Comment by amberdambey** [comment]
I know it's been over 6 years since this was opened, but this is still an issue, so it's unclear why this issue is closed. Please re-open it. It is affecting me on Parabola GNU/Linux-libre, on the latest version of Moonlight on flathub-floss (6.1.0), with KDE Plasma under Wayland. I had to set the libinput touchpad speed to almost zero for it to be usable. The IBM TrackPoint has a normal speed, and so does an external USB mouse. It's only the touchpad that seems to be problematic. Perhaps is there a way to configure how Moonlight polls mouse data? I can't find any setting for it in the GUI or in the Moonlight.conf file.

I did see 2 hotkeys in the help guide; neither of which are what I need:

> Ctrl+Alt+Shift+M - Toggle mouse mode (pointer capture or direct control)

This simply enables graphics-tablet-style cursor positioning, which would partially fix the touchpad problem but introduces many problems for the software I run. It also doesn't allow me to move my cursor off the edge of my primary display.

> Ctrl+Alt+Shift+C - Toggle local cursor display in remote desktop mouse mode (remote cursor will always show up due to GameStream limitations)

This does not appear to do anything. I assume the graphics-tablet mode is referred to here as the "remote desktop mouse mode", although even when in that mode, this hotkey does nothing.

As I previously stated, I just can't find anything to change within Moonlight itself to change polling behavior.

**Comment by KassFlute** [comment]
It is still an issue for me. Did someone found a solution on this ? As amberdambey said, why is this issue closed ?

**Comment by sammothxc** [comment]
I am also having the same issue with flatpak Moonlight on Asahi Linux Fedora Remix with KDE Plasma under Wayland. The Macbook trackpad goes way too fast, while an external USB mouse works normally.

**Comment by darioque** [comment]
Just installed it, both client and host are cachy OS linux machines on Xorg and same issue, laptop's touchpad moves the PC's cursor waaay too fast.

**Comment by hardwareadictos** [comment]
Same issue here
