### ISSUE TITLE
There was a lot of distortion in the sound.

### ISSUE THREAD

**Issue by LibertyGM** [moonlight-stream/moonlight-qt#1529]
After extreme system updates, the sound began to work with severe distortion.

I am attaching a video to understand the problem.

sunshine here:
Windows 11
Processor: i7-10700k
Graphics Processor: NVIDIA GeForce RTX 3070Ti

moonlight here:
Operating System: Arch Linux 
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.2
Kernel Version: 6.12.10-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × Intel® Core™ i9-14900KF
Memory: 62.6 ГиБ of RAM
Graphics Processor: NVIDIA GeForce RTX 4080/PCIe/SSE2
Manufacturer: ASUS

https://github.com/user-attachments/assets/06e33d9f-36a3-4adf-820a-14f3d95da3df

**Comment by svenstaro** [comment]
I'm 99% sure it's this: https://github.com/libsdl-org/sdl2-compat/issues/304#issuecomment-2631242079

Probably not a moonlight issue but a sdl2-compat issue. Probably best addressed over there.

**Comment by svenstaro** [comment]
This should be fixed upstream. Can you guys test?

**Comment by LibertyGM** [comment]
> This should be fixed upstream. Can you guys test?

If you mean sdl2-compat, then there is a problem with version 2.30.52. We need to wait for the release of the next stable version.

**Comment by svenstaro** [comment]
At any rate, the issue in this repo should be closed as this is not a moonlight issue and it's also been fixed in sdl2-compat upstream.

**Comment by LibertyGM** [comment]
> At any rate, the issue in this repo should be closed as this is not a moonlight issue and it's also been fixed in sdl2-compat upstream.

If you are sure that the problem has been solved, then close it.

**Comment by skicrafft** [comment]
i have same problem on arch linux ...

**Comment by Piket95** [comment]
> > i have same problem on arch linux ...
> 
> check if you still have /var/cache/pacman/pkg/sdl2-compat-2.30.51-1.1-x86_64_v4.pkg.tar.zst
> 
> if so you can do
> 
> `sudo pacman -U /var/cache/pacman/pkg/sdl2-compat-2.30.51-1.1-x86_64_v4.pkg.tar.zst`
> 
> to rollback to previous version. when you -Syu to do system update exclude sdl2-compat-2.30.52 if it's listed until the next stable version, 2.30.53 is released.
> 
> if you know how and you cannot wait for stable release, you can compile the latest head from the sdl2-compat github which should also temporarily resolve the issue until an updated stable release is out

Had the same problem. Reverting sdl2 to version 2.30.51 like you mentioned solved this issue temporary for me. Waiting on a official update then and hope it gets fixed by them.

To be exact I reverted to this still existing package in my pacman cache:
"sdl2-compat-2.30.51-1-x86_64.pkg.tar.zst"

**Comment by skicrafft** [comment]
> > > i have same problem on arch linux ...
> > 
> > 
> > check if you still have /var/cache/pacman/pkg/sdl2-compat-2.30.51-1.1-x86_64_v4.pkg.tar.zst
> > if so you can do
> > `sudo pacman -U /var/cache/pacman/pkg/sdl2-compat-2.30.51-1.1-x86_64_v4.pkg.tar.zst`
> > to rollback to previous version. when you -Syu to do system update exclude sdl2-compat-2.30.52 if it's listed until the next stable version, 2.30.53 is released.
> > if you know how and you cannot wait for stable release, you can compile the latest head from the sdl2-compat github which should also temporarily resolve the issue until an updated stable release is out
> 
> Had the same problem. Reverting sdl2 to version 2.30.51 like you mentioned solved this issue temporary for me. Waiting on a official update then and hope it gets fixed by them.
> 
> To be exact I reverted to this still existing package in my pacman cache: "sdl2-compat-2.30.51-1-x86_64.pkg.tar.zst"

I don't have this file anymore unfortunately, would you have the ability to send it to me somehow?

**Comment by svenstaro** [comment]
You can always get it from the archive: https://archive.archlinux.org/packages/s/sdl2-compat/

**Comment by svenstaro** [comment]
This should be closed as it's fixed in SDL upstream.
