### ISSUE TITLE
No sound on external audio devices on MacOS

### ISSUE THREAD

**Issue by Cludch** [moonlight-stream/moonlight-qt#351]
**Describe the bug**
I have no audio when using my MacBook as guest pc. If I use the MacBook without external headsets attached, everything works fine through the internal speakers. If I close the lid, attach the MacBook to a external display and attach my external headset, no sound is being display. Even though I set it as default audio output device.

**Steps to reproduce**
Set external output device. Start Moonlight and connect to the host pc and play any audio.

**Other Moonlight clients**
Only occurs on MacOS.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?: Yes
- If so, which settings have been changed?: 1080p, 144 Hz
- Does the problem still occur after reverting settings back to default?: Yes

**Client PC details (please complete the following information)**
 - OS: MacOS 10.15
 - Moonlight Version: v1.2.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 1910
 - GeForce Experience version: Latest
 - Nvidia GPU driver: Latest

**Moonlight Logs (please attach)**
[Moonlight-1583750380.log](https://github.com/moonlight-stream/moonlight-qt/files/4306159/Moonlight-1583750380.log)

**Additional**
It used to work on my old MacBook with the same external headset.
The logs state that no matching channel layout is found?

**Comment by cgutman** [comment]
Interesting. Can you try closing Moonlight then starting it again from the Terminal app like this:

```
ML_AUDIO=SDL /Applications/Moonlight.app/Contents/MacOS/Moonlight
```

See if the issue persists

**Comment by Cludch** [comment]
This fixes it. Thanks a lot, atleast I can stream on my MacBook now!
Even though the audio library issue should be resolved in the future.

**Comment by fuyar** [comment]
I have the same thing whenever I switch to a BT headset.
I somewhat managed to make it work by restarting moonlight completely.

**Comment by shalak** [comment]
I've been using Moonlight on MacOS with USB headphones for over a year with no issues. 

Today the audio stopped working...
- I tried with two different hosts,
- I tried rebooting both client and hosts
- I tried enabling/disabling audio-on-host, 
- I updated both client and drivers on host,

The above didn't solve the issue. However, running via `ML_AUDIO=SDL /Applications/Moonlight.app/Contents/MacOS/Moonlight` **does the trick and works around the issue**! 

@cgutman what does this `ML_AUDIO` env variable do? Why is it helping?

**Comment by cgutman** [comment]
Moonlight has a variety of audio backends. The `ML_AUDIO` variable allows you to switch between them.

By default, `libsoundio` is used on Windows and macOS for its lower latency, while `SDL` is the default for Linux due to better compatibility with the variety of Linux audio libraries.

There must be something wrong with the CoreAudio implementation in libsoundio, though I've never been able to reproduce the issue myself to report it to the maintainers of libsoundio. It's a very elusive bug. So far, you and the OP are the only two people known to have encountered it (@fuyar 's issue was different - switching audio devices on macOS, which was fixed in Moonlight v3.0.0). I've tried all sorts of things: built-in speakers, 3.5mm headphones, Bluetooth speakers, Bluetooth earbuds, AirPlay to an Apple TV, and I can't break the audio like what's described in this bug.

Can you provide as much information as possible about your audio devices and their configurations?

**Comment by shalak** [comment]
Here are my audio devices as seen in the System Report of About This Mac. 

```
Devices:

Arctis Pro Wireless Chat:

  Default Input Device:	Yes
  Default Output Device:	Yes
  Default System Output Device:	Yes
  Input Channels:	1
  Manufacturer:	SteelSeries 
  Output Channels:	1
  Current SampleRate:	48000
  Transport:	USB
  Input Source:	Default
  Output Source:	Default

Arctis Pro Wireless Game:

  Manufacturer:	SteelSeries 
  Output Channels:	2
  Current SampleRate:	48000
  Transport:	USB
  Output Source:	Default

MacBook Pro Microphone:

  Input Channels:	1
  Manufacturer:	Apple Inc.
  Current SampleRate:	48000
  Transport:	Built-in
  Input Source:	MacBook Pro Microphone

MacBook Pro Speakers:

  Manufacturer:	Apple Inc.
  Output Channels:	2
  Current SampleRate:	48000
  Transport:	Built-in
  Output Source:	MacBook Pro Speakers

```

The headset is connecting wirelessly (via proprietary protocol) to the base station, which is connected to the mac via USB.

After disconnecting the USB station, audio is being streamed properly to the built-in speakers. Like I mentioned, this issue started to appear yesterday, previously I was using those headphones without any issues.

How can I generate some logs for you to investigate?

**Comment by JulianLepinski** [comment]
@cgutman I've run into this issue myself, and, after some digging, I think I have a reliable reproduction scenario. In my case, I'm playing on macOS 11.6 on an Intel MacBook Pro, running Moonlight 3.1.4, and I'm reproducing this with AirPods.

It appears that the key issue here is how the AirPods (and presumably other audio devices) show up to Moonlight when they're capturing audio. What was initially causing this to happen on my end was a voice call in Telegram — if the call was established *before* launching a game in Moonlight, I'd get no audio from the game. If the call was established *after* launching the game, audio would come through fine. To simplify reproduction, I've verified that this also occurs if I start an audio recording in QuickTime before launching a game.

Here's an excerpt from my logs when audio is *not* being captured in QuickTime and things work as expected in Moonlight:

```
00:00:07 - SDL Info (0): Audio backend: CoreAudio
00:00:07 - SDL Info (0): Selected audio device: Julian’s AirPods
00:00:07 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:07 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:08 - SDL Info (0): Audio latency: 0.000000
00:00:08 - SDL Info (0): Audio channel count: 2
00:00:08 - SDL Info (0): Audio channel mask: 3

[...]

00:00:13 - SDL Info (0): Starting audio stream...
00:00:13 - SDL Info (0): Audio backend: CoreAudio
00:00:13 - SDL Info (0): Selected audio device: Julian’s AirPods
00:00:13 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:13 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:13 - SDL Info (0): Received first video packet after 0 ms
00:00:13 - SDL Info (0): Unrecoverable frame 4: 5+1=6 received < 13 needed
00:00:13 - SDL Info (0): Unrecoverable frame 5: 7+3=10 received < 13 needed
00:00:13 - SDL Info (0): Network dropped 2 frames (frames 4 to 5)
00:00:13 - SDL Info (0): Waiting for IDR frame
00:00:13 - SDL Info (0): IDR frame request sent
00:00:13 - SDL Info (0): Waiting for IDR frame
00:00:14 - SDL Info (0): Audio stream has 2 channels
```

And here's the same log lines when QuickTime was recording prior to launching the game and Moonlight has no audio:

```
00:00:07 - SDL Info (0): Audio backend: CoreAudio
00:00:07 - SDL Info (0): Selected audio device: Julian’s AirPods
00:00:07 - SDL Warn (0): No compatible channel layouts found. Some channels may not be played!
00:00:07 - SDL Info (0): Native layout: Mono (1 channels)
00:00:07 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:08 - SDL Info (0): Audio latency: 0.000000
00:00:08 - SDL Info (0): Audio channel count: 2
00:00:08 - SDL Info (0): Audio channel mask: 3

[...]

00:00:16 - SDL Info (0): Starting audio stream...
00:00:16 - SDL Info (0): Audio backend: CoreAudio
00:00:16 - SDL Info (0): Selected audio device: Julian’s AirPods
00:00:16 - SDL Warn (0): No compatible channel layouts found. Some channels may not be played!
00:00:16 - SDL Info (0): Native layout: Mono (1 channels)
00:00:16 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:16 - SDL Info (0): Received first video packet after 0 ms
00:00:17 - SDL Info (0): Audio stream has 2 channels
```

When starting Moonlight with `ML_AUDIO=SDL` set, I get similar behaviour but slightly different logs. In the case where I'm recording audio prior to startup, I see these log lines:

```
00:00:21 - SDL Error (0): Failed to open audio device: CoreAudio error (AudioQueueStart): -66681
00:00:21 - SDL Info (0): Audio channel count: 2
00:00:21 - SDL Info (0): Audio channel mask: 3
```

Moonlight also pops up [this notification](https://github.com/moonlight-stream/moonlight-qt/blob/d2c9f058f81d3ef5639369d3ff026d0a9e0c60fe/app/streaming/session.cpp#L706), and I typically get a burst of extremely loud static:
<img width="421" alt="Screen Shot 2021-11-05 at 6 29 02 PM" src="https://user-images.githubusercontent.com/53574915/140585506-bb653794-dff1-4cdc-9072-e9ef8d4c80be.png">

**Comment by cgutman** [comment]
Hmm, this probably has to do with the OS transition between Bluetooth profiles from A2DP (for music) or HFP (for calling). Perhaps macOS does something different if there's already audio playing on the device when the call is initiated?

**Comment by JulianLepinski** [comment]
That's interesting — I wonder if it's the same issue reported above (with the USB wireless headset) or simply looks the same. Is it expected that `audioTestPassed` is correctly being set to false with the `SDL` backend but not with `libsoundio`?

I'm happy to gather more info on my end, but I'm not familiar with the codebase — so let me know if there's anything specific you want.

**Comment by annamaaae** [comment]
Having a similar problem as this. Occasionally the ML_AUDIO=SDL occasionally works, sometimes it doesn't.

**Comment by cgutman** [comment]
SDL is now the default audio backend in Moonlight v3.2.0.

**Comment by fpetzold** [comment]
The bug still persists in Moonlight 4.1.0. Also with ML_AUDIO=SDL /Applications/Moonlight.app/Contents/MacOS/Moonlight

**Comment by cgutman** [comment]
Please file a new issue if you still see this bug in v4.2.1, since the original issue was specific to the libsoundio backend which is no longer in use. Please include Moonlight logs and System Report output for audio devices.

**Comment by miv** [comment]
I started to have this issue. Everything worked ok for a while but couple of days ago moonlight stoped sending audio to my Penroses. Long story short: install [Blackhole](https://existential.audio/blackhole/), create Multi-Output device with blackhole and your headphones and viola - sound returned.

There's probably some edge cases with handling USB sound devices.
